# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the phy drivers.
#


obj-$(CONFIG_GPIO_TM_DRIVER)		+= gpio-tutorial/	
obj-$(CONFIG_ADC_CUSTOM_TM_DRIVER)  += ads1115-custom/
obj-$(CONFIG_USB_CUSTOM_TM_DRIVER)  += usb-custom/