# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the phy drivers.
#


obj-$(CONFIG_GPIO_TM_DRIVER)		+= gpio-tutorial/	
obj-$(CONFIG_ACDC_I2C_TM_DRIVER)	+= acdc-i2c-tutorial/
obj-$(CONFIG_ADC_CUSTOM_TM_DRIVER)  += adc-custom/